Override symlinks if they exists
audstanley/NodeJs-Raspberry-Pi pull request #2
Opened 2016-01-05 02:19 UTC by m4recek

If there was previous version of node instaled then symlinks already exists

2017-01-31 07:51 UTC, audstanley approved these changes

2018-03-30 04:27 UTC, facastagnini commented
I think that using update-alternatives is a more elegant way to handle the destination of the links #11

2018-04-09 16:15 UTC, audstanley approved these changes

2018-04-09 16:27 UTC, audstanley requested changes
Looks great.  Start a new pull request with changes made to Install-Node.sh.  You edited Install-Node-MongoDb-Pi.sh which the script is now just a NodeJs installation.  I dropped support for mongo a long time ago since it should be a separate process for mongoDb.  I'm going to close, and merge once you make changes to the newer script.  I want you to get credit for the work.

2018-04-09 16:29 UTC, closed without merging